### ISSUE TITLE
password_reset_complete login link goes to /accounts/login not /admin

### ISSUE THREAD

**Issue by jlev** [tiborhari/django-admin-reset#1]
First, thanks for this library. It's the only solution that worked for me with Django 2.0 and a custom admin_site. The instructions at https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#adding-a-password-reset-feature did not work for me due to namespacing issues.

But, when using django-admin-reset and finishing the reset flow at `/admin/auth/user/password_reset_complete/done/` the Login link goes to `/accounts/login/`. With my single page app, I'm only having Django render the `/admin/` urls, so this caused some confusion. I was able to add a redirect to catch it, but it seems like the final login link should be namespaced back to the admin site, not the generic account login page.

**Comment by tiborhari** [comment]
Hi, thanks for the feedback. I've changed the link, so now it points to the login page of the admin site.
