### ISSUE TITLE
PASSWORD_RESET_TIMEOUT_DAYS is deprecated

### ISSUE THREAD

**Issue by intrepidclass** [tiborhari/django-admin-reset#10]
Hi!

PASSWORD_RESET_TIMEOUT_DAYS has been deprecated a while ago and has been removed in Django 4.
However, it is still listed in the instructions of this app.

The appropriate setting is now PASSWORD_RESET_TIMEOUT which is in seconds

Also, since I have set PASSWORD_RESET_TIMEOUT to 604800 in my app (which is 7 days), the password reset page that shows the reset link for a user in the admin says: This link can be sent [...] and it expires in 604800 days.

Can we make that either '604800 seconds' or better yet '7 days' ?

By the way, if I still try to use PASSWORD_RESET_TIMEOUT_DAYS, that settings seems to be ignored because then it says " and it expires in 259200 days." (which is the default 3 days instead of 604800 which would be 7 days)

**Comment by tiborhari** [comment]
Thanks for the report. This is now fixed in version 0.7.0.

**Comment by intrepidclass** [comment]
Thank you!
